async function createDepixelizeModule(moduleArg={}){var moduleRtn;var l=moduleArg;const {createRequire:aa}=await import("node:module");var require=aa(import.meta.url),m=(a,b)=>{throw b;},t=import.meta.url,u="",v,w,fs=require("node:fs");t.startsWith("file:")&&(u=require("node:path").dirname(require("node:url").fileURLToPath(t))+"/");w=a=>{a=x(a)?new URL(a):a;return fs.readFileSync(a)};v=async a=>{a=x(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);m=(a,b)=>{process.exitCode=a;throw b;};
var ba=console.log.bind(console),y=console.error.bind(console),z,A=!1,x=a=>a.startsWith("file://"),C,ca,D,E,F,G,H,I,da,ea,fa,ha,ia=!1;function ja(){var a=J.buffer;D=new Int8Array(a);F=new Int16Array(a);l.HEAPU8=E=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);da=new Float32Array(a);ea=new Float64Array(a);fa=new BigInt64Array(a);ha=new BigUint64Array(a)}
function ka(a){a="Aborted("+a+")";y(a);A=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ca?.(a);throw a;}var K;async function la(a){if(!z)try{var b=await v(a);return new Uint8Array(b)}catch{}if(a==K&&z)a=new Uint8Array(z);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}async function ma(a){var b=K;try{var c=await la(b);return await WebAssembly.instantiate(c,a)}catch(d){y(`failed to asynchronously prepare wasm: ${d}`),ka(d)}}
async function na(a){return ma(a)}class oa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}class pa{constructor(a){this.I=a-24}}var qa=0,ra=0,L=a=>{for(var b="";;){var c=E[a++];if(!c)return b;b+=String.fromCharCode(c)}},M={},N={},O={},P=class extends Error{constructor(a){super(a);this.name="BindingError"}};
function sa(a,b,c={}){var d=b.name;if(!a)throw new P(`type "${d}" must have a positive integer typeid pointer`);if(N.hasOwnProperty(a)){if(c.K)return;throw new P(`Cannot register type '${d}' twice`);}N[a]=b;delete O[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(e=>e()))}function Q(a,b,c={}){return sa(a,b,c)}
var ta=(a,b,c)=>{switch(b){case 1:return c?d=>D[d]:d=>E[d];case 2:return c?d=>F[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];case 8:return c?d=>fa[d>>3]:d=>ha[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},ua=[],R=[0,1,,1,null,1,!0,1,!1,1],va=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=ua.pop()||R.length;R[b]=a;R[b+1]=1;return b}};function S(a){return this.C(I[a>>2])}
var wa={name:"emscripten::val",C:a=>{if(!a)throw new P(`Cannot use deleted val. handle = ${a}`);var b=R[a];9<a&&0===--R[a+1]&&(R[a]=void 0,ua.push(a));return b},G:(a,b)=>va(b),H:S,F:null},xa=(a,b)=>{switch(b){case 4:return function(c){return this.C(da[c>>2])};case 8:return function(c){return this.C(ea[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ya=(a,b)=>Object.defineProperty(b,"name",{value:a});
function za(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].F)return!0;return!1}
function Aa(a,b,c,d){var e=b.length;if(2>e)throw new P("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==b[1]&&!1,h=za(b),g=!b[0].L,k=e-2,n=Array(k),p=[],q=[];return ya(a,function(...T){q.length=0;p.length=f?2:1;p[0]=d;if(f){var B=b[1].G(q,this);p[1]=B}for(var r=0;r<k;++r)n[r]=b[r+2].G(q,T[r]),p.push(n[r]);T=c(...p);if(h)for(;q.length;)B=q.pop(),q.pop()(B);else for(r=f?1:2;r<b.length;r++){var Ga=1===r?B:n[r-2];null!==b[r].F&&b[r].F(Ga)}B=g?b[0].C(T):void 0;
return B})}
var Ba=(a,b)=>{if(void 0===l[a].D){var c=l[a];l[a]=function(...d){if(!l[a].D.hasOwnProperty(d.length))throw new P(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${l[a].D})!`);return l[a].D[d.length].apply(this,d)};l[a].D=[];l[a].D[c.J]=c}},Ca=(a,b,c)=>{if(l.hasOwnProperty(a)){if(void 0===c||void 0!==l[a].D&&void 0!==l[a].D[c])throw new P(`Cannot register public name '${a}' twice`);Ba(a,a);if(l[a].D.hasOwnProperty(c))throw new P(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);l[a].D[c]=
b}else l[a]=b,l[a].J=c},Da=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c},Ea=class extends Error{constructor(a){super(a);this.name="InternalError"}},Ha=(a,b)=>{a=L(a);var c=Fa.get(b);if("function"!=typeof c)throw new P(`unknown function pointer with signature ${a}: ${b}`);return c};class Ia extends Error{}
var Ka=a=>{a=Ja(a);var b=L(a);U(a);return b},La=(a,b)=>{function c(f){e[f]||N[f]||(O[f]?O[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Ia(`${a}: `+d.map(Ka).join([", "]));},Ma=(a,b)=>{function c(g){g=b(g);if(g.length!==d.length)throw new Ea("Mismatched type converter count");for(var k=0;k<d.length;++k)Q(d[k],g[k])}var d=[];d.forEach(g=>O[g]=a);var e=Array(a.length),f=[],h=0;for(let [g,k]of a.entries())N.hasOwnProperty(k)?e[g]=N[k]:(f.push(k),M.hasOwnProperty(k)||(M[k]=[]),
M[k].push(()=>{e[g]=N[k];++h;h===f.length&&c(e)}));0===f.length&&c(e)},Na=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},V=(a,b,c)=>{var d=E;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|
f&63;e++}}d[b]=0}},Oa=new TextDecoder,W=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},Pa=new TextDecoder("utf-16le"),Qa=(a,b,c)=>{a>>=1;return Pa.decode(G.subarray(a,W(G,a,b/2,c)))},Ra=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d},Sa=a=>2*a.length,Ta=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=I[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Ua=(a,
b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;H[b>>2]=f;b+=4;if(b+4>c)break}H[b>>2]=0;return b-d},Va=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},X={},Wa=a=>{if(!A)try{a()}catch(b){b instanceof oa||"unwind"==b||m(1,b)}finally{}},Xa=[null,[],[]];l.wasmBinary&&(z=l.wasmBinary);
var Ja,Y,U,Ya,J,Fa,Za={c:(a,b,c)=>{var d=new pa(a);I[d.I+16>>2]=0;I[d.I+4>>2]=b;I[d.I+8>>2]=c;qa=a;ra++;throw qa;},u:()=>ka(""),g:(a,b,c,d,e)=>{b=L(b);d=0n===d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}Q(a,{name:b,C:f,G:(h,g)=>{"number"==typeof g&&(g=BigInt(g));return g},H:ta(b,c,!d),F:null})},j:(a,b,c,d)=>{b=L(b);Q(a,{name:b,C:function(e){return!!e},G:function(e,f){return f?c:d},H:function(e){return this.C(E[e])},F:null})},h:a=>Q(a,wa),f:(a,b,c)=>{b=L(b);Q(a,{name:b,C:d=>d,G:(d,
e)=>e,H:xa(b,c),F:null})},e:(a,b,c,d,e,f)=>{var h=Da(b,c);a=L(a);a=Na(a);e=Ha(d,e);Ca(a,function(){La(`Cannot call ${a} due to unbound types`,h)},b-1);Ma(h,g=>{var k=[g[0],null].concat(g.slice(1));g=a;k=Aa(a,k,e,f);var n=b-1;if(!l.hasOwnProperty(g))throw new Ea("Replacing nonexistent public symbol");void 0!==l[g].D&&void 0!==n?l[g].D[n]=k:(l[g]=k,l[g].J=n);return[]})},b:(a,b,c,d,e)=>{b=L(b);let f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}Q(a,{name:b,C:f,G:(g,k)=>k,H:ta(b,c,0!==d),F:null})},
a:(a,b,c)=>{function d(f){return new e(D.buffer,I[f+4>>2],I[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=L(c);Q(a,{name:c,C:d,H:d},{K:!0})},i:(a,b)=>{b=L(b);Q(a,{name:b,C(c){var d=(d=c+4)?Oa.decode(E.subarray(d,W(E,d,I[c>>2],!0))):"";U(c);return d},G(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new P("Cannot pass non-string to std::string");
if(f)for(var h=e=0;h<d.length;++h){var g=d.charCodeAt(h);127>=g?e++:2047>=g?e+=2:55296<=g&&57343>=g?(e+=4,++h):e+=3}else e=d.length;h=Y(4+e+1);g=h+4;I[h>>2]=e;f?V(d,g,e+1):E.set(d,g);null!==c&&c.push(U,h);return h},H:S,F(c){U(c)}})},d:(a,b,c)=>{c=L(c);if(2===b){var d=Qa;var e=Ra;var f=Sa}else d=Ta,e=Ua,f=Va;Q(a,{name:c,C:h=>{var g=d(h+4,I[h>>2]*b,!0);U(h);return g},G:(h,g)=>{if("string"!=typeof g)throw new P(`Cannot pass non-string to C++ string type ${c}`);var k=f(g),n=Y(4+k+b);I[n>>2]=k/b;e(g,n+
4,k+b);null!==h&&h.push(U,n);return n},H:S,F(h){U(h)}})},l:(a,b)=>{b=L(b);Q(a,{L:!0,name:b,C:()=>{},G:()=>{}})},m:()=>{},n:(a,b)=>{X[a]&&(clearTimeout(X[a].id),delete X[a]);if(!b)return 0;var c=setTimeout(()=>{delete X[a];Wa(()=>Ya(a,performance.now()))},b);X[a]={id:c,M:b};return 0},o:(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();I[a>>2]=60*Math.max(f,e);H[b>>2]=Number(f!=e);b=h=>{var g=Math.abs(h);return`UTC${0<=h?"-":"+"}${String(Math.floor(g/
60)).padStart(2,"0")}${String(g%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(V(a,c,17),V(b,d,17)):(V(a,d,17),V(b,c,17))},q:a=>{var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-J.buffer.byteLength+65535)/65536|0;try{J.grow(d);ja();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:()=>52,p:()=>52,r:function(){return 70},s:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var h=
I[b>>2],g=I[b+4>>2];b+=8;for(var k=0;k<g;k++){var n=a,p=E[h+k],q=Xa[n];0===p||10===p?(n=1===n?ba:y,p=W(q,0),p=Oa.decode(q.buffer?q.subarray(0,p):new Uint8Array(q.slice(0,p))),n(p),q.length=0):q.push(p)}e+=g}I[d>>2]=e;return 0},k:a=>{m(a,new oa(a))}},Z;
Z=await (async function(){var a={a:Za};K??=l.locateFile?l.locateFile?l.locateFile("depixelize.wasm",u):u+"depixelize.wasm":(new URL("depixelize.wasm",import.meta.url)).href;a=Z=(await na(a)).instance.exports;Ja=a.x;Y=a.y;U=a.z;Ya=a.B;J=a.v;Fa=a.A;ja();return Z}());l.calledRun=!0;A||(ia=!0,Z.w(),C?.(l));ia?moduleRtn=l:moduleRtn=new Promise((a,b)=>{C=a;ca=b});
;return moduleRtn}export default createDepixelizeModule;
